### ISSUE TITLE
Module loads settings.json, which hard-codes REST calls to US1 Platform

### ISSUE THREAD

**Issue by pandackindley** [techservicesillinois/SecOps-Powershell-Qualys#57]
**Description**

On module import, settings.json is read to set script-scoped variables to the URLs in the JSON payload. This is what Invoke-QualysRestCall uses to construct API URLs. The hosts defined in settings.json correspond to the US1 Platform of the Qualys API, meaning that any customers who are on different platforms must edit settings.json to be able to authenticate and access their Qualys APIs. See [this page](https://www.qualys.com/platform-identification/) for information about the different Qualys platforms.

**To Reproduce**

1. Be a Qualys customer on a platform that is not US1.
2. Import module with `Import-Module` or `using module`.
3. Perform an action against the Qualys API with a module cmdlet.
4. You will receive authentication errors.

**Expected behavior**
Users can either supply their region, or a query based on API service account username is made to identify the correct region and endpoints.

**Desktop (please complete the following information):**

- OS: Windows 10
- PowerShell 7.4

**Comment by edthedev** [comment]
In similar situations, we have updated the modules to check for environment variables, and only use the settings file if no environment variables are set.

@pandackindley Would having the module look first in `$env` before looking into `$settings.json` address your use case?

**Comment by pandackindley** [comment]
That's a good idea and would work for us. I updated the first line in the PSM1 to be a few lines instead:

`$Script:Settings = Get-Content -Path "$PSScriptRoot\settings.json" | ConvertFrom-Json

# Check $env:BasicAuthURI and $env:BaseURI and set $script:Settings.BasicAuthURI and $script:Settings.BaseURI from environment variables if present
# This will override the settings.json file if required.
if ($env:BasicAuthURI) {
    $script:Settings.BasicAuthURI = $env:BasicAuthURI
}
if ($env:BaseURI) {
    $script:Settings.BaseURI = $env:BaseURI
}`

That allows an automation to configure overrides to settings.json without impacting existing behavior. I'll update the docs and address in a future PR to version 1.7.1 after my current PR is merged. Thanks for the idea!

**Comment by edthedev** [comment]
Per our discussion in #56, this issue was also addressed in #56. Feel free to re-open if there's more we want to do with this.
