### ISSUE TITLE
Remove Sync-QualysTagAssignment

### ISSUE THREAD

**Issue by baristaTam** [techservicesillinois/SecOps-Powershell-Qualys#59]
This module is a wrapper for the Qualys API. We should not have accepted a sync function as in scope for this module. This would be best suited for a separate repo. Keeping this functionality in this module would complicate how we maintain this repo.

**Comment by baristaTam** [comment]
For discussion: the class objects may not belong in this repo either. For maintainability of this module, we don't want API calls in unexpected places. API calls related to a function should be contained within the function definition.

**Comment by edthedev** [comment]
@baristaTam  @pandackindley 

I do think we should also remove the class object creation from the the `Get-` function returns, for consistency with the rest of the API.

I've made this type of change in other modules, and just added a loop in the code that calls the module, to convert the raw responses into helper objects. 

In cases where that approach was too slow, I have added an option to inject a function that gets called on the result.

**Comment by edthedev** [comment]
@edthedev Talking to myself now, so I don't forget. In some cases I've used injection for before, I probably should have just exposed the APIs native paging options, instead, when available.

**Comment by edthedev** [comment]
Quick update after our ensemble - we think we will keep the class objects and just remove any methods that make additional API calls, to prepare of the next release.

@pandackindley This should keep it reasonable to continue to use your Sync script, with a little cleverness to inflate the more advanced object from the simpler one included here. We would be delighted to collaborate in realtime on that last bit, if you like. While we want to keep this repo simple, we certainly also want to ensure your use cases remain working.
